import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <span>За допомогою react, react redux (если кто хочет next использовать) вивести погоду 
          <a href="http://api.openweathermap.org/data/2.5/weather?q=LVIV&units=metric&APPID=5d066958a60d315387d9492393935c19">
            api.openweathermap.org
          </a>
        </span>
        <li>q=XXX - місто, для якого показати погоду</li>
        <li>temp – температура</li>
        <li>pressure - тиск</li>
        <li>description – опис</li>
        <li>humidity – вологість</li>
        <li>speed – швидкість вітру</li>
        <li>deg - напрям у градусах</li>
        <li>icon - значок, де 10d код іконки <a href="http://openweathermap.org/img/w/10d.png">openweathermap</a></li>
      </main>
    </>
  )
}
